assets: "https://wet-boew.github.io/themes-dist/GCWeb"
baseurl: "https://delisma.github.io/blog-dto"
defaults:
  -
    values:
      i18n:
          tmpl-lang-dir:
            en: ltr
            fr: ltr
markdown: kramdown
remote_theme: wet-boew/gcweb-jekyll
title: Canada.ca Blog